spring:
  config:
    activate:
      on-profile: prd
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  redis:
    session:
      host: ${SESSION_HOST}
      port: ${SESSION_PORT}
    cache:
      host: ${CACHE_HOST}
      port: ${CACHE_PORT}

server:
  port: 8080