spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
  session:
    store-type: redis
  redis:
    session:
      host: 127.0.0.1
      port: 6379
    cache:
      host: 127.0.0.1
      port: 6380

server:
  port: 8080